# Copyright 2025-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0

[package]
name = "vector-search-validator-vector-store"
version.workspace = true
edition.workspace = true

[dependencies]
scylla.workspace = true
tokio.workspace = true
tracing.workspace = true
vector-search-validator-tests.workspace = true
