# Copyright 2025-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0

[package]
name = "vector-search-validator"
version.workspace = true
edition.workspace = true

[dependencies]
vector-search-validator-engine.workspace = true
