# Copyright 2025-present ScyllaDB
# SPDX-License-Identifier: LicenseRef-ScyllaDB-Source-Available-1.0

[package]
name = "vector-search-validator-scylla"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vector-search-validator-tests.workspace = true
