name: Rust

on:
  push:
    branches:
    - 'master'

  pull_request:
    branches:
    - 'master'

  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  static_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy, rustfmt

    - name: Print rustc version
      run: rustc --version

    - name: Print rustfmt version
      run: cargo fmt --version

    - name: Print clippy version
      run: cargo clippy --version

    - name: Format check
      run: cargo fmt --all --check

    - name: Clippy check
      run: cargo clippy --all-targets --workspace -- -Dwarnings

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Print rustc version
      run: rustc --version

    - name: Run tests
      run: cargo test --features dev-tools --verbose --all-targets --workspace

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup cargo-deny
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-deny

    - name: Print cargo-deny version
      run: cargo deny --version

    - name: Run cargo-deny licenses checks
      run: cargo deny check

  cargo-machete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup cargo-machete
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-machete

    - name: Print cargo-machete version
      run: cargo machete --version

    - name: Run cargo-machete checks
      run: cargo machete
