name: Validator

on:
  push:
    branches:
    - 'master'

  pull_request:
    branches:
    - 'master'

  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup local rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Print release toolchain rustc version
      run: ./scripts/run-with-release-toolchain rustc --version

    - name: Build release
      run: ./scripts/run-with-release-toolchain cargo build --release --workspace

    - name: Run the Validator tests
      run: ./scripts/run-validator-with-scylla-docker scylladb/scylla-nightly target/amd64/release/vector-store target/amd64/release/vector-search-validator --verbose

